-- Clinical Study RAG + AI Observability Setup

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS CLINICAL_STUDY_AI_DB;
CREATE SCHEMA IF NOT EXISTS CLINICAL_STUDY_AI_DB.RAG;
CREATE SCHEMA IF NOT EXISTS CLINICAL_STUDY_AI_DB.OBSERVABILITY;

CREATE OR REPLACE WAREHOUSE CLINICAL_STUDY_AI_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE CLINICAL_STUDY_AI_WH;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ACCOUNTADMIN;
GRANT CREATE EXTERNAL AGENT ON SCHEMA CLINICAL_STUDY_AI_DB.OBSERVABILITY TO ROLE ACCOUNTADMIN;

CREATE OR REPLACE STAGE CLINICAL_STUDY_AI_DB.RAG.DOCUMENT_STAGE
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE OR REPLACE STAGE CLINICAL_STUDY_AI_DB.RAG.EVALUATION_STAGE
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE OR REPLACE FILE FORMAT CLINICAL_STUDY_AI_DB.RAG.CSV_FORMAT
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  EMPTY_FIELD_AS_NULL = TRUE
  TRIM_SPACE = TRUE
  ENCODING = 'UTF8';

-- Upload only:
-- 01_RECOVERY_Trial_Protocol_V28_10.pdf
-- 04_RECOVERY_Data_Monitoring_Committee_Charter.pdf
-- 06_RECOVERY_Participant_Information_and_Consent.pdf
-- 07_RECOVERY_Follow_Up_Case_Report_Form.pdf
-- 08_RECOVERY_Serious_Adverse_Event_Form.pdf

CREATE OR REPLACE TABLE CLINICAL_STUDY_AI_DB.RAG.PARSED_DOCUMENTS AS
SELECT
    RELATIVE_PATH AS FILE_NAME,
    TO_VARCHAR(
      SNOWFLAKE.CORTEX.PARSE_DOCUMENT(
        @CLINICAL_STUDY_AI_DB.RAG.DOCUMENT_STAGE,
        RELATIVE_PATH,
        {'mode':'LAYOUT'}
      ):content
    ) AS PARSED_TEXT,
    CURRENT_TIMESTAMP() AS PARSED_AT
FROM DIRECTORY(@CLINICAL_STUDY_AI_DB.RAG.DOCUMENT_STAGE)
WHERE LOWER(RELATIVE_PATH) LIKE '%.pdf';

CREATE OR REPLACE TABLE CLINICAL_STUDY_AI_DB.RAG.DOCUMENT_CHUNKS (
    CHUNK_ID VARCHAR,
    FILE_NAME VARCHAR,
    DOCUMENT_TYPE VARCHAR,
    CHUNK_INDEX NUMBER,
    CHUNK VARCHAR,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO CLINICAL_STUDY_AI_DB.RAG.DOCUMENT_CHUNKS
    (CHUNK_ID, FILE_NAME, DOCUMENT_TYPE, CHUNK_INDEX, CHUNK)
SELECT
    SHA2(FILE_NAME || '|' || F.INDEX || '|' || F.VALUE::VARCHAR, 256),
    FILE_NAME,
    CASE
      WHEN FILE_NAME ILIKE '%Protocol%' THEN 'TRIAL_PROTOCOL'
      WHEN FILE_NAME ILIKE '%Monitoring%Committee%' THEN 'DMC_CHARTER'
      WHEN FILE_NAME ILIKE '%Participant%Information%' OR FILE_NAME ILIKE '%Consent%' THEN 'PARTICIPANT_INFORMATION'
      WHEN FILE_NAME ILIKE '%Follow%Up%' THEN 'FOLLOW_UP_CRF'
      WHEN FILE_NAME ILIKE '%Adverse%Event%' THEN 'SAE_FORM'
      ELSE 'OTHER'
    END,
    F.INDEX,
    F.VALUE::VARCHAR
FROM CLINICAL_STUDY_AI_DB.RAG.PARSED_DOCUMENTS,
LATERAL FLATTEN(
  INPUT => SNOWFLAKE.CORTEX.SPLIT_TEXT_RECURSIVE_CHARACTER(
      PARSED_TEXT,
      'markdown',
      1400,
      200
  )
) F;

CREATE OR REPLACE CORTEX SEARCH SERVICE
  CLINICAL_STUDY_AI_DB.RAG.CLINICAL_STUDY_SEARCH_SERVICE
  ON CHUNK
  ATTRIBUTES FILE_NAME, DOCUMENT_TYPE
  WAREHOUSE = CLINICAL_STUDY_AI_WH
  TARGET_LAG = '1 hour'
  EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
AS
SELECT CHUNK, FILE_NAME, DOCUMENT_TYPE, CHUNK_INDEX
FROM CLINICAL_STUDY_AI_DB.RAG.DOCUMENT_CHUNKS;

CREATE OR REPLACE TABLE CLINICAL_STUDY_AI_DB.OBSERVABILITY.CLINICAL_STUDY_EVAL_DATA (
    QUERY VARCHAR,
    GROUND_TRUTH_RESPONSE VARCHAR
);

COPY INTO CLINICAL_STUDY_AI_DB.OBSERVABILITY.CLINICAL_STUDY_EVAL_DATA
FROM @CLINICAL_STUDY_AI_DB.RAG.EVALUATION_STAGE
FILE_FORMAT = (FORMAT_NAME = CLINICAL_STUDY_AI_DB.RAG.CSV_FORMAT)
PATTERN = '.*Eval_dataset_recovery_clinical_study[.]csv'
ON_ERROR = 'ABORT_STATEMENT';

SELECT DOCUMENT_TYPE, COUNT(*) AS CHUNK_COUNT
FROM CLINICAL_STUDY_AI_DB.RAG.DOCUMENT_CHUNKS
GROUP BY DOCUMENT_TYPE
ORDER BY DOCUMENT_TYPE;

SELECT COUNT(*) AS EVALUATION_QUESTION_COUNT
FROM CLINICAL_STUDY_AI_DB.OBSERVABILITY.CLINICAL_STUDY_EVAL_DATA;
